name: Deploy HTML to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Show all files
      run: ls -al

    - name: SSH to EC2
      uses: appleboy/ssh-action@v1
      with:
          host: ${{ secrets.EC2_INSTANCE }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            whoami
            pwd
            ls -al
            mkdir gundeep_retry
